# -*- coding: utf-8 -*-
#
# Copyright (C) 2018 CERN.
#
# KPIit is free software; you can redistribute it and/or modify it
# under the terms of the MIT License; see LICENSE file for more details.

version: '2.3'
services:
  worker:
    build:
      context: ./
    restart: "always"
    command: "/opt/kpiit/src/scripts/server"
    image: kpiit
    environment:
      - "BROKER_URL=redis://broker:6379/0"
      - "CELERY_RESULT_BACKEND=redis://broker:6379/1"
    links:
      - broker
  broker:
    image: redis
    restart: "always"
    read_only: true
    ports:
      - "6379:6379"
  flower:
    image: mher/flower
    command: --broker=redis://localhost:6379/0
    ports:
      - "5555:5555"
    links:
      - broker
