{
 "title": "dr-kpi-test-1",
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   { "name": "env", "label": "Environment", "query": "qa, prod" },
   { "name": "service", "label": "Service", "query": "zenodo, cds_videos, cod" }
  ]
 },
 "panels": [
  {
   "title": "Records",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Number of records" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "repokpi",
     "select": [
      [
       { "params": [ "records" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "total_records" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$env$/" },
      { "condition": "AND", "key": "service", "operator": "=~", "value": "/^$service$/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "repokpi",
     "query": "SELECT difference(mean(\"records\")) FROM \"raw\".\"repokpi\" WHERE (\"env\" =~ /^$env$/ AND \"service\" =~ /^$service$/) AND $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "records" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       {
        "params": [],
        "type": "difference"
       },
       { "params": [ "new_records" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$env$/" },
      { "condition": "AND", "key": "service", "operator": "=~", "value": "/^$service$/" }
     ]
    }
   ]
  },
  {
   "title": "Storage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "bytes", "label": "TB" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "quota_usage",
     "query": "SELECT sum(\"used_bytes\") AS \"allocated\", sum(\"used_bytes\") / sum(\"max_bytes\") AS \"ratio\"\nFROM \"raw\".\"quota_usage\"\nWHERE (\n    ('$service' = '(zenodo|cds_videos|cod)' AND \"path\" =~ /^\\/eos\\/media\\/(zenodo|cds)\\/$/)\n    OR\n    ('$service' = 'zenodo' AND \"path\" =~ /^\\/eos\\/media\\/zenodo\\/$/)\n    OR\n    ('$service' = 'cds_videos' AND \"path\" =~ /^\\/eos\\/media\\/cds\\/$/)\n    OR\n    ('$service' = 'cod' AND \"path\" =~ /^\\/eos\\/media\\/zenodo\\/$/)\n) AND $timeFilter\nGROUP BY time($__interval) fill(previous)",
     "select": [
      [
       { "params": [ "used_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "allocated" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=", "value": "media" },
      { "condition": "AND", "key": "path", "operator": "=~", "value": "/^\\/eos\\/media\\/zenodo\\/$/" }
     ]
    }
   ]
  },
  {
   "title": "New Records Table",
   "type": "table",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "repokpi",
     "query": "SELECT difference(mean(\"records\"))\nFROM \"raw\".\"repokpi\"\nWHERE (\"env\" =~ /^$env$/ AND \"service\" =~ /^$service$/)\nAND $timeFilter\nGROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "records" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$env$/" },
      { "condition": "AND", "key": "service", "operator": "=~", "value": "/^$service$/" }
     ]
    }
   ]
  },
  {
   "title": "Visits",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short", "label": "Visits" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "repokpi",
     "select": [
      [
       { "params": [ "visits" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "visits" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$env$/" },
      { "condition": "AND", "key": "service", "operator": "=~", "value": "/^$service$/" },
      { "condition": "AND", "key": "visits", "operator": ">", "value": "-1" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "repokpi",
     "select": [
      [
       { "params": [ "visits_unique" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "unique_visits" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$env$/" },
      { "condition": "AND", "key": "service", "operator": "=~", "value": "/^$service$/" },
      { "condition": "AND", "key": "unique_visits", "operator": ">", "value": "-1" }
     ]
    }
   ]
  },
  {
   "title": "DOI resolutions",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 9 },
   "yaxes": [
    { "format": "short", "label": "Successful" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "doikpi",
     "query": "SELECT sum(\"doi_success\") AS successful, sum(\"doi_failed\") AS failed\nFROM \"raw\".\"doikpi\"\nWHERE (\n    ('$service' = '(zenodo|cds_videos|cod)' AND (\"doi_prefix\" = '10.5281' OR \"doi_prefix\" = '10.17181' OR \"doi_prefix\" = '10.7484'))\n    OR\n    ('$service' = 'zenodo' AND \"doi_prefix\" = '10.5281')\n    OR\n    ('$service' = 'cds_videos' AND \"doi_prefix\" = '10.17181')\n    OR\n    ('$service' = 'cod' AND \"doi_prefix\" = '10.7483')\n) AND $timeFilter\nGROUP BY time(1h) fill(none)",
     "select": [
      [
       { "params": [ "*" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "doi_prefix", "operator": "=", "value": "select tag value" }
     ]
    }
   ]
  },
  {
   "title": "Uptime (Web)",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 5, "x": 0, "y": 18 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "repokpi",
     "select": [
      [
       { "params": [ "uptime_web" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$env$/" },
      { "condition": "AND", "key": "service", "operator": "=~", "value": "/^$service$/" }
     ]
    }
   ]
  },
  {
   "title": "Uptime (Search)",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 5, "x": 5, "y": 18 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "repokpi",
     "select": [
      [
       { "params": [ "uptime_search" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$env$/" },
      { "condition": "AND", "key": "service", "operator": "=~", "value": "/^$service$/" }
     ]
    }
   ]
  },
  {
   "title": "Uptime (Files)",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 5, "x": 10, "y": 18 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "repokpi",
     "select": [
      [
       { "params": [ "uptime_files" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$env$/" },
      { "condition": "AND", "key": "service", "operator": "=~", "value": "/^$service$/" }
     ]
    }
   ]
  }
 ]
}