apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: '2'
    kompose.cmd: kompose convert
    kompose.version: 1.13.0 (84fa826)
  creationTimestamp: '2018-07-10T12:28:38Z'
  generation: 1
  labels:
    io.kompose.service: broker
  name: broker
  namespace: it-cda-dr-kpis
  resourceVersion: '333868179'
  selfLink: /apis/apps/v1/namespaces/it-cda-dr-kpis/deployments/broker
  uid: c5daee48-843c-11e8-b019-fa163ea7aa03
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: broker
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: broker
    spec:
      containers:
        - image: redis
          imagePullPolicy: Always
          name: broker
          ports:
            - containerPort: 6379
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  collisionCount: 1
  conditions:
    - lastTransitionTime: '2018-07-10T12:28:38Z'
      lastUpdateTime: '2018-07-10T12:28:38Z'
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: 'True'
      type: Available
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
