#!/usr/bin/env python
import argparse
import logging
import subprocess


logger = logging.getLogger('openshift_deploy')
logger.setLevel(logging.DEBUG)

ch = logging.StreamHandler()
logger.addHandler(ch)


class DeploymentError(Exception):
    def __init__(self, title, message):
        self.title = title
        self.message = message


def check_openshift_auth():
    result = subprocess.run(
        ['oc', 'whoami'],
        stderr=subprocess.PIPE,
        stdout=subprocess.DEVNULL
    )
    if result.returncode != 0:
        logger.error('Not authenticated with OpenShift')
        raise DeploymentError('OpenShift Auth Failed',
                              result.stderr.decode('utf-8'))


def check_docker_auth():
    cmd = 'docker login -u openshift -p $(oc whoami -t) openshift-registry.web.cern.ch'
    result = subprocess.run(
        cmd,
        shell=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.DEVNULL
    )
    msg = result.stdout.decode('utf-8')
    if msg != 'Login Succeeded\n':
        logger.error('Not authenticated with Docker')
        raise DeploymentError('Docker Auth Failed',
                              result.stdout.decode('utf-8'))


def run_command(cmd, args):
    output = subprocess.PIPE if args.verbose else subprocess.DEVNULL

    cmd_kwargs = dict(stdout=output, stderr=output)

    if args.verbose:
        result = subprocess.run(cmd, shell=True)
    else:
        result = subprocess.run(cmd, shell=True, **cmd_kwargs)

    if result.returncode != 0:
        raise DeploymentError('Command Failed', cmd)


def build_docker_image(args):
    cmd = 'docker build --no-cache=true --network=host -t {image} .'.format(
        image=args.image
    )
    logger.debug('Build command: %s' % cmd)
    logger.info('Building docker image...')

    run_command(cmd, args)

    logger.debug('Docker image build was successful.')


def tag_docker_image(args):
    cmd = 'docker tag {image_tag} {registry}/{image}'.format(
        image_tag=args.image,
        registry=args.registry,
        image=args.image.split(':')[0]
    )
    logger.debug('Tag command: %s' % cmd)
    logger.info('Tagging docker image...')

    run_command(cmd, args)

    logger.debug('Docker tag was successful.')


def push_docker_image(args):
    cmd = 'docker push {registry}/{image}'.format(
        registry=args.registry,
        image=args.image.split(':')[0]
    )
    logger.debug('Push command: %s' % cmd)
    logger.info('Pushing docker image to OpenShift...')

    run_command(cmd, args)

    logger.debug('Docker image was successfully pushed to OpenShift.')


def setup():
    check_openshift_auth()
    check_docker_auth()

    default_image = 'kpiit-image:latest'
    default_registry = 'openshift-registry.web.cern.ch/it-cda-dr-kpis'

    parser = argparse.ArgumentParser()
    parser.add_argument(
        '--image', '-i',
        default=default_image,
        help='docker image name (default: {})'.format(default_image)
    )
    parser.add_argument(
        '--registry', '-r',
        default=default_registry,
        help='OpenShift docker registry (default: {})'.format(default_registry)
    )
    parser.add_argument(
        '--build-only', '-b',
        action='store_true',
        help='build the Docker image without pushing it to OpenShift'
    )
    parser.add_argument(
        '--verbose', '-v',
        action='store_true',
        help='verbose output messages'
    )

    return parser.parse_args()


if __name__ == '__main__':
    try:
        args = setup()

        build_docker_image(args)
        tag_docker_image(args)

        if not args.build_only:
            push_docker_image(args)

    except DeploymentError as de:
        print('[{title}] {msg}'.format(title=de.title, msg=de.message))
    except KeyboardInterrupt:
        logger.info('Exiting...')
