apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.13.0 (84fa826)
  creationTimestamp: null
  labels:
    io.kompose.service: flower
  name: flower
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: flower
    spec:
      containers:
      - args:
        - --broker=redis://localhost:6379/0
        image: mher/flower
        name: flower
        ports:
        - containerPort: 5555
        resources: {}
      restartPolicy: Always
status: {}
